deep sleep: workaround for false negative case

diff --git a/skeleton/SYSTEM/tg5040/bin/suspend b/skeleton/SYSTEM/tg5040/bin/suspend
--- a/skeleton/SYSTEM/tg5040/bin/suspend
+++ b/skeleton/SYSTEM/tg5040/bin/suspend
@@ -54,21 +54,38 @@ after() {
 before
 
 >&2 echo "Suspending..."
-sleep_max_tries=10
+sleep_max_tries=5
 for i in $(seq 1 $sleep_max_tries); do
-  >&2 echo "Deep sleep attempt $i of $sleep_max_tries"
+	>&2 echo "Deep sleep attempt $i of $sleep_max_tries"
 
-  # Can't use | true here, it would crash out on non-zero return.
-  echo mem >/sys/power/state
-  sleep_retval=$?
+	sleep_time=$(date +%s)
+	echo mem >/sys/power/state
+	sleep_retval=$?
 
-  >&2 echo "Deep sleep: kernel returned $sleep_retval"
-  if [ $sleep_retval -eq 0 ]; then
-     break
-  fi
+	>&2 echo "Deep sleep: kernel returned $sleep_retval"
+	if [ $sleep_retval -eq 0 ]; then
+		break
+	fi
 
-  >&2 echo "Deep sleep failed: retrying in 2 seconds"
-  sleep 2
+	wake_time=$(date +%s)
+	time_asleep=$(($wake_time-$sleep_time))
+
+	# Workaround for a strange false negative case where
+	# the device sleeps properly but still returns non-zero.
+	# If unaddressed, the device would sleep again immediately
+	# after the user tried to wake it.
+
+	# If device has been asleep for longer than a set period,
+	# ignore the retval and continue with waking the device.
+	if [ $time_asleep -gt 5 ]; then
+		>&2 echo "Deep sleep: averting false negative retval - (sleep for $time_asleep secs)"
+		sleep_retval=0
+		break
+	fi
+	
+
+	>&2 echo "Deep sleep failed: retrying in 3 seconds"
+	sleep 3
 done
 
 # Resume services in background to reduce UI latency
diff --git a/skeleton/SYSTEM/tg5050/bin/suspend b/skeleton/SYSTEM/tg5050/bin/suspend
--- a/skeleton/SYSTEM/tg5050/bin/suspend
+++ b/skeleton/SYSTEM/tg5050/bin/suspend
@@ -54,11 +54,10 @@ after() {
 before
 
 >&2 echo "Suspending..."
-sleep_max_tries=10
+sleep_max_tries=5
 for i in $(seq 1 $sleep_max_tries); do
 	>&2 echo "Deep sleep attempt $i of $sleep_max_tries"
 
-	# Can't use | true here, it would crash out on non-zero return.
 	echo mem >/sys/power/state
 	sleep_retval=$?
 
@@ -67,8 +66,8 @@ for i in $(seq 1 $sleep_max_tries); do
 	    break
 	fi
 
-	>&2 echo "Deep sleep failed: retrying in 2 seconds"
-	sleep 2
+	>&2 echo "Deep sleep failed: retrying in 3 seconds"
+	sleep 3
 done
 
 # Resume services in background to reduce UI latency
