chore: indentation

diff --git a/skeleton/SYSTEM/tg5040/bin/suspend b/skeleton/SYSTEM/tg5040/bin/suspend
--- a/skeleton/SYSTEM/tg5040/bin/suspend
+++ b/skeleton/SYSTEM/tg5040/bin/suspend
@@ -73,38 +73,38 @@ before
 >&2 echo "Suspending..."
 sleep_max_tries=10
 for i in $(seq 1 $sleep_max_tries); do
-  >&2 echo "Deep sleep attempt $i of $sleep_max_tries"
+	>&2 echo "Deep sleep attempt $i of $sleep_max_tries"
 
-  sleep_time=$(date +%s)
-  
-  # Can't use | true here, it would crash out on non-zero return.
-  echo mem >/sys/power/state
-  sleep_retval=$?
+	sleep_time=$(date +%s)
+	
+	# Can't use | true here, it would crash out on non-zero return.
+	echo mem >/sys/power/state
+	sleep_retval=$?
 
-  >&2 echo "Deep sleep: kernel returned $sleep_retval"
-  if [ $sleep_retval -eq 0 ]; then
-     break
-  fi
+	>&2 echo "Deep sleep: kernel returned $sleep_retval"
+	if [ $sleep_retval -eq 0 ]; then
+		break
+	fi
 
-  # Really hard to debug this edge case where the system sleeps successfully
-  # but still returns nonzero
-  wake_time=$(date +%s)
+	# Really hard to debug this edge case where the system sleeps successfully
+	# but still returns nonzero
+	wake_time=$(date +%s)
 
-  time_asleep=$(($wake_time-$sleep_time))
+	time_asleep=$(($wake_time-$sleep_time))
 
-  if [ $time_asleep -gt 5 ]; then
-	  >&2 echo "Deep sleep: bug caught - (sleep for $time_asleep secs)"
-	  sleep_retval=0
-	  wakeup
-  fi
-  
+	if [ $time_asleep -gt 5 ]; then
+		>&2 echo "Deep sleep: bug caught - (sleep for $time_asleep secs)"
+		sleep_retval=0
+		wakeup
+	fi
+	
 
-  >&2 echo "Deep sleep failed: retrying in 2 seconds"
-  waitforwake.elf 2
-  if [ $? -eq 1 ]; then
-	  sleep_retval=0
-	  wakeup
-  fi
+	>&2 echo "Deep sleep failed: retrying in 2 seconds"
+	waitforwake.elf 2
+	if [ $? -eq 1 ]; then
+		sleep_retval=0
+		wakeup
+	fi
 done
 
 # api.c: if sleep_retval is still non-zero at this point
